// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABEaA8jnJikgMmBKb987ruUWNTORvPRzY',
    appId: '1:922658300638:android:d814c603d18fb2b7dc984f',
    messagingSenderId: '922658300638',
    projectId: 'selaty-app-c0729',
    databaseURL: 'https://selaty-app-c0729-default-rtdb.firebaseio.com',
    storageBucket: 'selaty-app-c0729.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ghDcRCKU8PowMPL1c5nHHB8ZOPk1Oy8',
    appId: '1:922658300638:ios:0ab83609aa2e0210dc984f',
    messagingSenderId: '922658300638',
    projectId: 'selaty-app-c0729',
    databaseURL: 'https://selaty-app-c0729-default-rtdb.firebaseio.com',
    storageBucket: 'selaty-app-c0729.appspot.com',
    iosBundleId: 'com.example.selatyApp',
  );
}
